### ISSUE TITLE
pseudo classes

### ISSUE THREAD

**Issue by tbrannam** [tolo/InterfaCSS#18]
I'd propose supporting pseudo classes that allow styling on device form factor.
as a minimum "phone". "tablet" - 

I could see perhaps following the pattern of size-classes instead (width-compact, width-any, width-regular, height-compact, height-any, height-regular)?

It might also be helpful if the Pseudo Class Parse supported multiple Pseudo Classes in a style definition - or is there another way to express this already?

    .simple:phone:landscape{
        backgroundColor: red;
    }

    .simple:phone:portrait{
        backgroundColor: blue;
    }

    .simple:tablet:portrait{
        backgroundColor: pink;
    }
    .simple:tablet:landscape{
        backgroundColor: green;
    }

**Comment by tbrannam** [comment]
Adding multiple Pseudoclass support came just in time.  Thanks!

**Comment by tolo** [comment]
Glad to hear it! :)
