### ISSUE TITLE
Stylesheet parser - multithreaded

### ISSUE THREAD

**Issue by tbrannam** [tolo/InterfaCSS#20]
I see that a singleton Stylesheet parser is kept by InterfaCSS - do you think it would be thread safe to create another instance if the Parser to parse data in a worker thread?  I think the only thing lost in this case would be CSS constant definitions (@stuff: "stuff").   

Clearly the UIView styling passes need to be in the UI thread - but do you think the parsing, factory stuff could be threaded safely?

**Comment by tolo** [comment]
Sorry for the late reply - pretty much disconnected myself during the holidays.

It should be possible to make parsing concurrent. I had in fact planned to do that from the beginning to avoid locking up the UI when parsing, but after I completed the first round of parsing optimizations I kind of forgot about that. But I'm going to look into supporting async parsing, while at the same time supporting constants properly.
