### ISSUE TITLE
Feature: Remote images

### ISSUE THREAD

**Issue by tbrannam** [tolo/InterfaCSS#21]
When parsing styles, it would be good to have a way to delegate the loading of images.  

Specifically - I'm thinking about allowing remote images to be specified in the image style markup.   This likely has implications for layout or layout managers.

**Comment by tbrannam** [comment]
It would seem that this feature would depend on allowing the value transformation to be asynchronous.  I'm using a different file format, so I'm able to hook and insert a custom subclass of ISSPropertyDeclaration for images.   Perhaps the transformatValueIfNeeded should be given the target from applyPropertyValueOnTarget?  (Or perhaps the lazyPropertyTransformationBlock could get a reference to the target?) 

    ISSPropertyDeclaration's 
    - (BOOL) transformValueIfNeeded;
    - (BOOL) applyPropertyValueOnTarget:(id)target;

**Comment by tolo** [comment]
Interesting - I'll look into adding support to delegate loading of images and possibly some sort of hook for customizing property declaration creation.
