### ISSUE TITLE
override or extend registered properties

### ISSUE THREAD

**Issue by tbrannam** [tolo/InterfaCSS#28]
I have been trying to extend some properties to support UIControlState (tintColor) for a custom control.   But it appears that a duplicate custom property does not get called - it would be great if custom properties would get called - ideally with the setter block for the original implementation - so that the original implementation could get called in the event that the override's special doesn't have to reimplement the original version.

**Comment by tolo** [comment]
Great idea - I'll certainly look into this.

**Comment by tbrannam** [comment]
similarly it would be nice to be able to modify typeToParser

For example, if I want to add a new fontFunctionParser I would think I could modify 

    typeToParser[@(ISSPropertyTypeFont)] = [Parcoa choice:@[myCustomFontFunction, fontFunctionParser, fontValueParser]];

which would allow my to hook into processing for a font - and fallback to the other parsers.
