### ISSUE TITLE
Gradient UI color doesn't support named colors

### ISSUE THREAD

**Issue by tbrannam** [tolo/InterfaCSS#29]
UIColor - the wiki suggests that gradient can not be nested with other color functions, but I expected that named colors were treated as values, not functions.   The gradient parser does not get called when passing named colors.

Fails
`gradient(white, black)`
Succeeds
`gradient(rgb(255,255,255),rgb(0,0,0))`

**Comment by tolo** [comment]
Right, that support seemed to be missing. Good catch, thanks. A fix is underway.
