### ISSUE TITLE
ISSPropertyTypeNumber does not support negative numbers

### ISSUE THREAD

**Issue by tbrannam** [tolo/InterfaCSS#30]
NSAttributedStrings support a negative kern value, but the
ISSPropertyTypeNumber rejects negative numbers

**Comment by tolo** [comment]
What a coincidence - just stumbled into this myself the other day when implementing a new feature. I'll check in the fix in a while.

**Comment by tolo** [comment]
Fixed (by 2b33c11749b23688809dc3fdcd8d5c0b613e9d38).
