### ISSUE TITLE
Imposible to use in extension target

### ISSUE THREAD

**Issue by killobatt** [tolo/InterfaCSS#33]
When using `InterfaCSS` in a extension target, build fails: 
Implementation often relies on `UIApplication`, and `+sharedApplication` and other methods got attribute `NS_EXTENSION_UNAVAILABLE_IOS`

**Comment by tolo** [comment]
Right, good catch, thanks. I'll take a look at that, and I will also check if there are other potential issues with using InterfaCSS in extensions.
