### ISSUE TITLE
Could not find "Parcoa.h" when using CocoaPods 0.38.2 and use_frameworks!

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#34]
In the file `Parcoa+ISSAdditions.h` there is `#import "Parcoa.h"` which does not work with CocoaPods 0.38.2 and `use_frameworks!` directive. I managed to make it work by changing it to `#import <Parcoa/Parcoa.h>` but I'm not sure if this is the correct way.

**Comment by tolo** [comment]
Ah, good catch, thanks. I believe that will fix the problem - I'll include this in a maintenance release shortly.
