### ISSUE TITLE
Support for calc function.

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#35]
It would be nice if we could do some calculations in the stylesheet. For example I have a constant called `@gridStep` and I would like to do something like `cornerRadius: calc(@gridStep * 2);`. Currently I could not find a way to do this in ISS. Is it possible? Or would that feature be possible to add? Thanks.

**Comment by tolo** [comment]
Yes, that would be nice, and I have actually though a bit about this in the past (for instance when implementing ISSLayout). It shouldn't be too hard to add I think, so I will definitely look into doing that for the next feature release.
