### ISSUE TITLE
Using custom types as selectors.

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#36]
In Classy (which we used until now) you can use a custom view name as a selector. As we have a lot of custom views (deriving from UIView), it is a pain to a class name every where. Would this feature be possible?

**Comment by tbrannam** [comment]
Take a look at this sample CSS https://github.com/tolo/InterfaCSS/blob/master/Samples/SimpleSample/SimpleSample/main.css

you can specify a UIView class at the selector by using only the class name as the selector (without . or #)

**Comment by TadeasKriz** [comment]
I know, but as I said, these are only UIKit ones. I was asking about custom ones :)

**Comment by tbrannam** [comment]
Pretty sure it works for custom subclasses as well

**Comment by TadeasKriz** [comment]
It tells me it cannot find a view with that name (or something like that and the name is prepended with `UI`) :(

**Comment by tolo** [comment]
Yes, this is not supported at the moment unfortunately, however I don't think adding support for this should be too hard, so I'll look into doing that for the next feature release.

**Comment by TadeasKriz** [comment]
I have added some kind of support for custom "canonical type" in our fork, but I'm not sure if it is the way it should be implemented.
