### ISSUE TITLE
Faster file watching similar to what Classy have (to reapply the styles immediately after save)

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#38]

**Comment by tolo** [comment]
I actually had the intention of adding this when I implemented support for reloadable stylesheets, but at the time, I guess I prioritized reloading of remote stylesheets and kind of neglected the local stylesheets a bit. But instant reload upon file save would nice to have, so I'll definitely look into adding this.

**Comment by TadeasKriz** [comment]
Thanks! PS: Great library, with a few extra touches it will be totally unbeatable :)

**Comment by tolo** [comment]
Thanks, glad you like it! :) Yes, unbeatable is definitely what I'm aiming for! ;)
