### ISSUE TITLE
UIButton label is styled by UILabel style and cannot be overridden (apparently)

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#39]
Stylesheet:

```
Label {
    font: AFont 15;
}

UIButton {
    titleLabel.font: BFont 20;
}
```

Will yield a button with a label with font `AFont 15` instead of `BFont 20`. The order of style does not matter unfortunately. Or is this something that cannot be fixed?

**Comment by tolo** [comment]
Yes, this is indeed a problem (with how setting properties on child objects currently works), but a problem that can be fixed. In fact, I'm working on a solution now, in the development branch for the next release, that I'm hoping will fix this. But for now, you have to work around the problem, for instance by doing something like this: 

```
UIButton > UILabel {
    font: BFont 20;
}
```
