### ISSUE TITLE
UICollectionViewCell cannot be targeted as a descendant/child and doesn't get styled properly.

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#40]
I don't seem to get working this:

```
UICollectionViewCell {
    someProperty: value;
}

UIView.main {
    UICollectionViewCell {
        someProperty: otherValue;
    }
}
```

When doing this, the style does not get applied and also I need to call `UIView#scheduleApplyStylingISS` myself in the `dequeue` method of delegate. Is this a bug or something that cannot be fixed? Or is it something with my code?

PS: Applies to UITableView as well.

**Comment by tolo** [comment]
When using nested declarations (or descendant selector chains etc), one must make sure that the leaf element (i.e. cell in this case) is added to the view hierarchy before applying styles. Currently, InterfaCSS doesn't provide any automatic handling for this (this could be accomplished with some method swizzling magic, but I'm trying to avoid such things a much as possible), which means it has to be done manually. One way of doing that is to apply the styles in the `willDisplayCell` method of the table view / collection view delegate, another way is to do it in the `didMoveToSuperview` method of a custom cell subclass.

I admit, the documentation around this could perhaps be a bit better...

**Comment by TadeasKriz** [comment]
I'm still not able to make the styling work properly. Sometimes it works, sometimes it does not and it's frustrating. Some tableviews don't get styled until I touch them or scroll them. Please advise. Thanks.

**Comment by tolo** [comment]
Sorry to hear. I'm just in the process of improving documentation, and I am also planning on releasing version 1.1 soon, which will bring improvements along with a bunch of new features.

In the meantime, try this:
* Log active declarations for a view using this call `-[InterfaCSS logMatchingStyleDeclarationsForUIElement:]`
* Have a look at the SimpleSample demo application - that one uses a UITableView (see `PrototypeExampleViewController` / `prototypeExample.css`) with at least a moderately complex style setup
* Try and simplify your selectors, i.e. instead using selectors like `UITableView UITableViewCell .myClass`, try using just `.myCellClass` for instance

**Comment by tbrannam** [comment]
With regards to tableview cells - I noticed that my styles didn't get
applied when a new cell is allocated (not recycled) -- in this case the
cell has no superview yet.   In my case I manually called [tableView
addSubview:cell] inside my tableView:cellForRowAtIndexPath: if
cell.superview was nil.   This allowed my styling rules to match - which
included class for my UITableView.

**Comment by tolo** [comment]
Closing this as there doesn't seem to be an underlying problem and likely just a usage issue, which is now documented on the [wiki](https://github.com/tolo/InterfaCSS/wiki/Using-InterfaCSS#styling-of-cells-in-table-views-and-collection-views). 

Feel free to reopen the issue in case there are indications that there still are issues with table/collection view cells.
