### ISSUE TITLE
View in some UIViewController inside UITabBarController does not get styled before shown

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#41]
I have a UITabBarController with 5 tabs. When I switch to another tab, the views are not styled immediately, but after a fraction of a second. It is still visible though and you can see the style getting applied. Is this a bug of InterfaCSS or is it in my code?

**Comment by tolo** [comment]
Hard to say for sure, without knowing more about the particular setup. Have a look at the `SimpleSample` sample application - it uses a UITabBarController. 

Also, make sure styles are applied when the view of a view controller is about to appear - when using a `ISSRootView` as the root view of a view controller, this is handled automatically.

**Comment by TadeasKriz** [comment]
The `ISSRootView` seems to fix my problem with the noticeable styling, thanks for that, I missed its presence in the documentation, sorry about that.

**Comment by tolo** [comment]
Sweet, no worries!
