### ISSUE TITLE
Support for styling views by controller types.

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#42]
For example:

```
UITabBarController > UIView {
    backgroundColor: white;
}
```
Now I can't seem to find a way to style a root views (only by setting the styleClass for the view itself).

**Comment by tolo** [comment]
Currently, selectors are only matched against items in the view hierarchy, which means that declarations containing non-view types won't work. However, it could be useful to be able to express that kind of selector chain, so I will definitely consider adding support for this going forward.
