### ISSUE TITLE
UITextInputTraits' properties cannot be set using KVC

### ISSUE THREAD

**Issue by TadeasKriz** [tolo/InterfaCSS#43]
I'm getting errors when I try to set for example `keyboardType` (or other `UITextInputTraits` properties) from stylesheet. The error is that the `UITextInput` is not coding-compliant with the property's name (e.g. `keyboardType`). Is this a problem when using InterfaCSS with Swift or a bug even in ObjC?

**Comment by tolo** [comment]
Good catch, thanks. That was a bit unexpected - haven't seen that issue before (and it seems there wasn't good enough test coverage on those properties). I've fixed the issue in the development branch. I will merge into master and create a new release soon.
