### ISSUE TITLE
tvOS configuration

### ISSUE THREAD

**Issue by tbrannam** [tolo/InterfaCSS#44]
Apple added a few wrinkles to UIKit in the tvOS variation.   Do you have a style preference for how to remove unsupported methods?  Ifdef's - stub classes? macros?

I'll likely be sending a pull request in the next couple days with some of these edits as I get the rest of my project working.

**Comment by tolo** [comment]
I think ifdefs should probably do the trick, but we'll see. I've anyway just added preliminary support for tvOS (i.e. everything compiles for a tvOS target).
