### ISSUE TITLE
Support for UIStoryboardSegue

### ISSUE THREAD

**Issue by bangerang** [tolo/InterfaCSS#46]
Hi,

Is it possible to use an ```UIStoryboardSegue``` from a UIButton in Storyboard? It seems that InterfaCSS blocks my segue.
Code:
```
-(void)loadView
{
    [super loadView];
    self.view = [ISSViewBuilder rootViewWithStyle:@"sliderMainView" andSubViews:^NSArray *{
        return @[self.okBtn = [ISSViewBuilder buttonWithId:@"onboardingOkButton"]];
    }];
  

}
```

**Comment by tolo** [comment]
Well, what seems to happen here is that you are completely replacing
whatever you have set up in the storyboard (including segues) with a
different view hierarchy.

So the question is what your are tying to do here. If you only want to
assign an element id or style class to the views, you can do that directly
in the storyboard (via runtime attributes).

Cheers,
Tobias

**Comment by bangerang** [comment]
Hi Tobias,

Using an id was a stupid example. I want to use it as a general style schema.
I was actually unfamiliar with runtime attributes, good stuff!
It works when I set color and font. But when I try to set the frame in my css:
```frame: size(auto, 15%).bottom(0);``` nothing happens.
Is this the way to use this framework? I still want to use some storyboard features but avoid stuff like auto layout.

Best,
Johan

**Comment by tolo** [comment]
Hi Johan, 

You can now (1.3.1) also use properties exposed using `IBInspectable` (there was a bug that prevented this from working correctly before).

There are basically two ways you can do layout with InterfaCSS:
* Use absolute or parent relative [rects](https://github.com/tolo/InterfaCSS/wiki/Stylesheet-Property-Reference#CGRect) to set the `frame` property
* Using the slightly more powerful [ISSLayout](https://github.com/tolo/InterfaCSS/wiki/ISSLayout-Reference)    
    
    
Regardless of whatever approach you use, keep the following in mind:
* Whenever you use a storyboard or xib, make sure to disable stuff that can interfere with layout handled by InterfaCSS (i.e. make sure auto layout is disabled for the storyboard/xib, and disable view autoresizing if not needed).
* Using an `ISSRootView` as the root view of a view controller makes life easier (and is also required for ISSLayout).

Also, have a look at the sample code - that's usually a good place to start and to get inspiration (and then there is also the [wiki](https://github.com/tolo/InterfaCSS/wiki) of course). 

/Tobias

**Comment by bangerang** [comment]
Amazing Tobias, truly great work putting this together! The ```IBInspectable``` feature was just what I needed.

**Comment by tolo** [comment]
Thanks, glad you like it! :smiley:
