### ISSUE TITLE
Crash when using IQKeyboardManager

### ISSUE THREAD

**Issue by bangerang** [tolo/InterfaCSS#49]
I'm using a library called ```IQKeyboardManager``` (https://github.com/hackiftekhar/IQKeyboardManager). But when I select a textfield and use ```IQKeyboardManager```next function my app throws an exception at ```ISSUIElementDetails.m```:
<img width="763" alt="screen shot 2015-12-02 at 14 22 23" src="https://cloud.githubusercontent.com/assets/3526934/11531849/254cff5e-9900-11e5-9c0b-a2b5e9e90164.png">

I used this library before and it worked perfectly. Any idea what's causing this?
I would really love if these two great libraries could work together :)

**Comment by bangerang** [comment]
This also throws an exception:
```
 UIToolbar* numberToolbar = [[UIToolbar alloc]initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, 50)];
    numberToolbar.barStyle = UIBarStyleBlackTranslucent;
    numberToolbar.items = [NSArray arrayWithObjects:
                           [[UIBarButtonItem alloc]initWithTitle:@"Cancel" style:UIBarButtonItemStyleDone target:self action:@selector(cancelNumberPad)],
                           [[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace target:nil action:nil],
                           [[UIBarButtonItem alloc]initWithTitle:@"Done" style:UIBarButtonItemStyleDone target:self action:@selector(doneWithNumberPad)],
                           nil];
    [numberToolbar sizeToFit];
    
    UITextField *pnoField = [self.view subviewWithElementId:@"loginDetailsPersonalNumberInputField"];
    pnoField.inputAccessoryView = numberToolbar;
```
Same file:
<img width="758" alt="screen shot 2015-12-02 at 14 41 29" src="https://cloud.githubusercontent.com/assets/3526934/11532251/e8aa8758-9902-11e5-8677-baf4037e8e9e.png">

**Comment by tolo** [comment]
Well, I would of course love it if InterfaCSS played nice with other frameworks as well. :) So I'll have to investigate what the underlying reason for the crash is.
