### ISSUE TITLE
guide layout parameter - used but not well documented

### ISSUE THREAD

**Issue by ChrisInIssaquah** [tolo/InterfaCSS#55]
In the HelloISSLayout example file layout.css has entry
```
#layoutGuideLabel {
    layout: top(guide.top + 1), centerX(parent); 
}  
 
```  
I could not find anything in the Wiki that discussed **guide**.  Is there also a **guide.left**, **guide,right**, **guide.center** ?

**Comment by tolo** [comment]
Hi, 

The [Reference Attributes](../wiki/ISSLayout-Reference#reference-attributes) section on the ISSLayout Reference wiki page actually mentions this: 


> Valid layout guide attributes are as follows:
> * top
> * center
> * bottom

**Comment by ChrisInIssaquah** [comment]
Oops - missed that.

**Comment by tolo** [comment]
No worries ;)
